GAMES = {
    'F.1': 'ms1',
    'F.X': 'msx',
    'F.2': 'ms2',
    'H15.U': 'iyau1,5-alt',
    'H15.O': 'iyau1,5-ust',
    'F15.U': 'au1,5-alt',
    'F15.O': 'au1,5-ust',
    'UNDER': 'au2,5-alt',
    'OVER': 'au2,5-ust',
    'F35.U': 'au3,5-alt',
    'F35.O': 'au3,5-ust',
    'S.1': 'iy1',
    'S.X': 'iyx',
    'S.2': 'iy2',
    'DC.1X': 'cs1-x',
    'DC.X2': 'csx-2',
    'DC.12': 'cs1-2',
    'H.1': 'h1',
    'H.2': 'h2',
    'H.X': 'hx',
    'SF.11': 'iyms1/1',
    'SF.1X': 'iyms1/x',
    'SF.12': 'iyms1/2',
    'SF.X1': 'iymsx/1',
    'SF.XX': 'iymsx/x',
    'SF.X2': 'iymsx/2',
    'SF.21': 'iyms2/1',
    'SF.2X': 'iyms2/x',
    'SF.22': 'iyms2/2',
    'SC.GG': 'kgvar',
    'SC.NG': 'kgyok',
    'GS.01': 'tg0-1',
    'GS.23': 'tg2-3',
    'GS.46': 'tg4-6',
    'GS.7P': 'tg7+'
}

GAMES_LIST = [
    'tctek',
    'tccift',
    'ms1',
    'msx',
    'ms2',
    'iyau1,5-alt',
    'iyau1,5-ust',
    'au1,5-alt',
    'au1,5-ust',
    'au2,5-alt',
    'au2,5-ust',
    'au3,5-alt',
    'au3,5-ust',
    'iy1',
    'iyx',
    'iy2',
    'cs1-x',
    'csx-2',
    'cs1-2',
    'h1',
    'h2',
    'hx',
    'iyms1/1',
    'iyms1/x',
    'iyms1/2',
    'iymsx/1',
    'iymsx/x',
    'iymsx/2',
    'iyms2/1',
    'iyms2/x',
    'iyms2/2',
    'kgvar',
    'kgyok',
    'tg0-1',
    'tg2-3',
    'tg4-6',
    'tg7+'
]

GROUPED_GAMES_LIST = {
    'tctek': 'Tek Çift',
    'tccift': 'Tek Çift',
    'ms1': 'Maç Sonucu',
    'msx': 'Maç Sonucu',
    'ms2': 'Maç Sonucu',
    'iyau1,5-alt': 'İlk Yarı 1.5 Gol',
    'iyau1,5-ust': 'İlk Yarı 1.5 Gol',
    'au1,5-alt': 'Maç Sonu 1.5 Gol',
    'au1,5-ust': 'Maç Sonu 1.5 Gol',
    'au2,5-alt': 'Maç Sonu 2.5 Gol',
    'au2,5-ust': 'Maç Sonu 2.5 Gol',
    'au3,5-alt': 'Maç Sonu 3.5 Gol',
    'au3,5-ust': 'Maç Sonu 3.5 Gol',
    'iy1': 'İlk Yarı Sonucu',
    'iyx': 'İlk Yarı Sonucu',
    'iy2': 'İlk Yarı Sonucu',
    'cs1-x': 'Çifte Şans',
    'csx-2': 'Çifte Şans',
    'cs1-2': 'Çifte Şans',
    'h1': 'Handikap',
    'h2': 'Handikap',
    'hx': 'Handikap',
    'iyms1/1': 'İlk Yarı/Maç Sonu',
    'iyms1/x': 'İlk Yarı/Maç Sonu',
    'iyms1/2': 'İlk Yarı/Maç Sonu',
    'iymsx/1': 'İlk Yarı/Maç Sonu',
    'iymsx/x': 'İlk Yarı/Maç Sonu',
    'iymsx/2': 'İlk Yarı/Maç Sonu',
    'iyms2/1': 'İlk Yarı/Maç Sonu',
    'iyms2/x': 'İlk Yarı/Maç Sonu',
    'iyms2/2': 'İlk Yarı/Maç Sonu',
    'kgvar': 'Karşılıklı Gol',
    'kgyok': 'Karşılıklı Gol',
    'tg0-1': 'Toplam Gol',
    'tg2-3': 'Toplam Gol',
    'tg4-6': 'Toplam Gol',
    'tg7+': 'Toplam Gol',
}
