# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180328_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience_point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='remaining_modifier',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_point',
            field=models.IntegerField(default=0),
        ),
    ]
