# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill_point',
            field=models.FloatField(default=0),
        ),
    ]
