# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-06 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_monthly_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyscore',
            name='skill_point',
            field=models.IntegerField(default=0),
        ),
    ]
