# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_modify_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyscore',
            name='skill_point',
            field=models.FloatField(default=0),
        ),
    ]
