# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-28 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophytype',
            name='count',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
    ]
