# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_league_field'),
        ('trophy', '0002_trophy_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trophytype',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.League'),
            preserve_default=False,
        ),
    ]
