# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('substitution', 'Substitution'), ('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card')], max_length=100)),
                ('text', models.CharField(max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Match')),
            ],
        ),
    ]
