# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_auto_20180419_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='upvote',
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together=set([('match', 'user')]),
        ),
        migrations.AddField(
            model_name='upvote',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Prediction'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='upvoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set([('prediction', 'upvoter')]),
        ),
    ]
