# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180420_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='side',
            field=models.CharField(choices=[('home', 'Home'), ('away', 'Away')], default='home', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchevent',
            name='time',
            field=models.CharField(default='31', max_length=20),
            preserve_default=False,
        ),
    ]
