# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20180421_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='teams/logos', width_field='logo_width')),
                ('logo_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('logo_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='forum.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='forum.Team'),
        ),
    ]
