# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='iddaa_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
