# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_iddaa_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
