# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-14 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20180515_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='iddaa_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
