# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_first_half_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='handicap',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
